name: Synchronize source code

on:
  workflow_call:
    secrets:
      GITLAB_URL:
        required: true
      GITLAB_TRIGGER_TOKEN:
        required: true
      GITLAB_TOKEN:
        required: false
      GILTAB_PROJECT_NAME:
        required: true
      GITLAB_MIRROR_ID:
        required: true
    inputs:
      SYNC_ALL:
        type: string
        default: "true"
      BRANCH_NAME:
        type: string

      WAIT:
        type: boolean
        default: true
      CI_SKIP:
        type: boolean
        default: false

jobs:
  sync1:
    uses: ./.github/workflows/run-pipeline.yaml
    secrets:
      GITLAB_PROJECT_ID: ${{ secrets.GITLAB_MIRROR_ID }}
      GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_URL: ${{ secrets.GITLAB_URL }}
      CI_VARS: |
        PROJECT_NAME=${{ secrets.GILTAB_PROJECT_NAME }}
    with:
      REF: main
      WAIT: ${{ inputs.WAIT }}
      CI_VARS: |
        SYNC_ALL=${{ inputs.SYNC_ALL }}
        GIT_BRANCH_DEPLOY=${{ inputs.BRANCH_NAME }}
        CI_SKIP=${{ inputs.CI_SKIP }}

